mick/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',

	url(r'^$', 'main.views.home'),
	url(r'^thanks/$', 'main.views.thanks'), 
    # Examples:
    # url(r'^$', 'mick.views.home', name='home'),
    # url(r'^mick/', include('mick.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms

class Contact(forms.Form):

	name = forms.CharField(required=True, error_messages={'required': 'Please enter your full name'})
	subject = forms.CharField(required=True, error_messages={'required': 'Please enter a subject.'})
	email = forms.EmailField(required=True, error_messages={'required': 'Please enter a correct email'})
	message = forms.CharField(required=True, error_messages={'required': 'Please enter your message'},  widget=forms.Textarea(attrs={'class':'special'}))
    

main/views.py
from forms import Contact
from django.shortcuts import render, render_to_response


def home(request):        
	if request.method == 'POST':
	    form = Contact(request.POST)
	    if form.is_valid():
	        cleanData = form.cleaned_data	    
	        recipients = ['jonny@mustcreate.co.uk']
	    
	        from django.core.mail import send_mail
	        send_mail(
	        	cleanData['subject'], 
	        	cleanData['message'], 
	        	cleanData.get('email'), 
	        	recipients)
	        success = "Thank you!"
	        form = Contact()
	        return render_to_response( 'main/index.html', {'form': form, 'success': success})
	else:
	    form = Contact()
	return render(request, 'main/index.html', {
		'form': form
		})

def thanks(request): 
	if request.method == 'POST':
		success = "thanks"
		return render(request, 'main/index.html', {'form': form, 'success': success})
	else:
		return HttpResponseRedirect('/')

mick/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>Mick Ross </title>
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static "style/main.css"%}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src={% static "scripts/main.js"%}></script>
</head>
<body>
	{% block content %}
	{% endblock content %}
</body>
</html> 

mick/templates/main/index.html
{% extends "base.html" %}

{% block content %}

<div id="wrapper">
	<header class="main">
		<div>
			<h1>Mick Ross</h1>
		</div>
		<nav>
            <div id="anchor"></div>
			<ul>
				<li><a href="#work">Work</a></li>
				<li><a href="#about">About</a></li>
				<li><a href="#contact">Contact</a></li>
			</ul>
		</nav>
	</header>
	<section id="work">
		<ul id="carousel">
			<li data-album-name="album1" data-active="true">
				<div id="work-content"></div>
				<section id="album-details">
					<iframe id="album1" width="99%" height="415" src="http://www.youtube.com/embed/5VkopBuOXto?autohide=1&showinfo=0" frameborder="0" allowfullscreen></iframe>
					<div class="albumCopy">
                        <h2>Title of the Song<span class="artistName">Band Name</span></h2>
    					<P>
    						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, maxime, recusandae omnis doloribus illo dolore fugiat quidem velit inventore tempora magni assumenda labore rem! Aut, voluptates, quod, odio necessitatibus quaerat sequi aperiam in distinctio similique commodi pariatur exercitationem consequatur et cupiditate culpa at animi harum molestias ipsam aliquid quae esse repellendus quia odit consequuntur ducimus ullam ipsum dolore quam. 
    					</p>
                    </div>
				</section>
			</li>
			<li data-album-name="album2">
				<div id="work-content"></div>
				<section id="album-details">
                    <iframe id="album2" width="99%" height="415" src="http://www.youtube.com/embed/9bZkp7q19f0" frameborder="0" allowfullscreen></iframe>
                    <div class="albumCopy">
    					<h2>Title of the Song 2<span class="artistName">Band Name</span></h2>
    					<P>
    						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, maxime, recusandae omnis doloribus illo dolore fugiat quidem velit inventore tempora magni assumenda labore rem! Aut, voluptates, quod, odio necessitatibus quaerat sequi aperiam in distinctio similique commodi pariatur exercitationem consequatur et cupiditate culpa at animi harum molestias ipsam aliquid quae esse repellendus quia odit consequuntur ducimus ullam ipsum dolore quam. 
    					</p>
                    </div>
				</section>
			</li>
			<li data-album-name="album3">
				<div id="work-content"></div>
				<section id="album-details">
                    <iframe id="album3" width="99%" height="415" src="http://www.youtube.com/embed/9bZkp7q19f0" frameborder="0" allowfullscreen></iframe>
                    <div class="albumCopy">
    					<h2>Title of the Song 3<span class="artistName">Band Name</span></h2>
    					<P>
    						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, maxime, recusandae omnis doloribus illo dolore fugiat quidem velit inventore tempora magni assumenda labore rem! Aut, voluptates, quod, odio necessitatibus quaerat sequi aperiam in distinctio similique commodi pariatur exercitationem consequatur et cupiditate culpa at animi harum molestias ipsam aliquid quae esse repellendus quia odit consequuntur ducimus ullam ipsum dolore quam. 
    					</p>
                    </div>
				</section>
			</li>
			<li data-album-name="album4">
				<div id="work-content"></div>
				<section id="album-details">
                    <iframe id="album4" width="99%" height="415" src="http://www.youtube.com/embed/9bZkp7q19f0" frameborder="0" allowfullscreen></iframe>
                    <div class="albumCopy">
    					<h2>Title of the Song 4<span class="artistName">Band Name</span></h2>
    					<P>
    						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, maxime, recusandae omnis doloribus illo dolore fugiat quidem velit inventore tempora magni assumenda labore rem! Aut, voluptates, quod, odio necessitatibus quaerat sequi aperiam in distinctio similique commodi pariatur exercitationem consequatur et cupiditate culpa at animi harum molestias ipsam aliquid quae esse repellendus quia odit consequuntur ducimus ullam ipsum dolore quam. 
    					</p>
                    </div>
				</section>
			</li>
			<li data-album-name="album5">
				<div id="work-content"></div>
				<section id="album-details">
                    <iframe id="album5" width="99%" height="415" src="http://www.youtube.com/embed/9bZkp7q19f0" frameborder="0" allowfullscreen></iframe>
                    <div class="albumCopy">
    					<h2>Title of the Song 5<span class="artistName">Band Name</span></h2>
    					<P>
    						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, maxime, recusandae omnis doloribus illo dolore fugiat quidem velit inventore tempora magni assumenda labore rem! Aut, voluptates, quod, odio necessitatibus quaerat sequi aperiam in distinctio similique commodi pariatur exercitationem consequatur et cupiditate culpa at animi harum molestias ipsam aliquid quae esse repellendus quia odit consequuntur ducimus ullam ipsum dolore quam. 
    					</p>
                    </div>
				</section>
			</li>
			<li data-album-name="album6">
				<div id="work-content"></div>
				<section id="album-details">
                    <iframe id="album6" width="99%" height="415" src="http://www.youtube.com/embed/9bZkp7q19f0" frameborder="0" allowfullscreen></iframe>
                    <div class="albumCopy">
    					<h2>Title of the Song 6<span class="artistName">Band Name</span></h2>
    					<P>
    						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corrupti, maxime, recusandae omnis doloribus illo dolore fugiat quidem velit inventore tempora magni assumenda labore rem! Aut, voluptates, quod, odio necessitatibus quaerat sequi aperiam in distinctio similique commodi pariatur exercitationem consequatur et cupiditate culpa at animi harum molestias ipsam aliquid quae esse repellendus quia odit consequuntur ducimus ullam ipsum dolore quam. 
    					</p>
                    </div>
				</section>
			</li>
		</ul>
		<div id="album-nav">
			<ul>
				<li data-album-name="album1" data-active="true">
    		        <img src="/static/media/images/lovesick.jpeg" alt="album art for The Prison Library" />
				</li>
				<li data-album-name="album2">
    			    <img src="/static/media/images/newkids.jpeg" alt="album art for whatever this is" />
				</li>
				<li data-album-name="album3">
    			    <img src="/static/media/images/tlpoets.jpeg" alt="album art for this" />   
				</li>
				<li data-album-name="album4">
    			    <img src="/static/media/images/hunger.jpeg" alt="album art for whatever this is" />   
				</li>
				<li data-album-name="album5">
    			    <img src="/static/media/images/bmovie.jpeg" alt="album art for whatever this is" />   
				</li>
				<li data-album-name="album6">
    			    <img src="/static/media/images/happiness.jpeg" alt="album art for whatever this is" />   
				</li>
			</ul>
		</div>
	</section>
	<section id="about">
        <section id="description">
            <h2>About Mick Ross</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam vestibulum malesuada diam id tempus. Sed ut elit posuere tortor pellentesque dignissim. Mauris ornare ornare felis, non suscipit ipsum egestas ut. Quisque ornare aliquam ullamcorper. Suspendisse ac nibh est. Praesent vestibulum mi vel tortor sodales vel interdum sapien faucibus. Etiam porttitor dictum velit, sit amet pharetra tellus sodales at. Quisque tempus venenatis enim nec sodales. Nullam sed sagittis risus. Aenean sed metus ut nibh rutrum pulvinar.
            </p>
        </section>
	</section>
	<section id="contact">
        <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Old+Glassworks+Stepney+Bank,+Newcastle+upon+Tyne,+Tyne+and+Wear+NE1+2NP,+United+Kingdom+0191+423+9313&amp;aq=&amp;sll=54.939216,-1.599162&amp;sspn=0.681601,1.783905&amp;ie=UTF8&amp;hq=Old+Glassworks+Stepney+Bank,+Newcastle+upon+Tyne,+Tyne+and+Wear+NE1+2NP,+United+Kingdom+0191+423+9313&amp;hnear=&amp;t=m&amp;z=10&amp;iwloc=A&amp;cid=13667507701417562942&amp;ll=54.97525,-1.59355&amp;output=embed"></iframe>
        		<div class="contactForm">
	        		<form actions="/contact" method="post">
	        			{% csrf_token %}
	        			<h2>Contact</h2>
	        			<hr>
	                    {% if form.errors %}
	                    <ul id="errors"> 
	                        {% for field, error in form.errors.items %}
	                        <li>{{ error }}</li>
	                        {% endfor %}
	                    </ul>
	                    {% endif %}
	                    {% if success %}
	                    <span>{{ success }}</span>
	                    {% endif %}
	                    <div class="left">
	                    	<label for="id_name">Full Name</label>
	        		        {{ form.name }}
	                        <label for="id_email">Email</label>
	                    	{{ form.email }}
	                        <label for="id_subject">Subject</label>
	                    	{{ form.subject }}
	                    </div>
	                    <div class="right">
	                    	<label for="id_message">Message</label>
	                        {{ form.message }}
	                        <input type="submit" value="submit">
	                    </div>
	        		</form>
        		</div>
	    </section>
	<footer class="main"></footer>
</div>

{% endblock content %}